CREATE TABLE IF NOT EXISTS Book(
    id INT PRIMARY KEY AUTO_INCREMENT,
    book_title VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Author(
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    FOREIGN KEY (book_id) REFERENCES Book(id)
);